---
name: monorepo
on: 
  workflow_dispatch:
    inputs:
      test-tags:
        type: choice
        required: true
        description: 'Select test tag'
        options:
        - regression
        - letter-template
      environment:
        type: choice
        required: true
        description: 'Select test environment'
        options:
        - https://app.test.medirecords.com/
        - https://uitest.test.medirecords.com/

defaults:
  run:
    working-directory: test     

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          runTests: false
  lint:
    needs: install
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          working-directory: test
          install: false
      - run: npm run lint
  mrtest:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          working-directory: test
          runTests: false
      - uses: cypress-io/github-action@v5
        with:
          working-directory: test
          install: false
          wait-on: '${{inputs.environment}}'
          browser: ${{ matrix.browser }}
          record: false
          parallel: false
          config: "baseUrl=${{inputs.environment}}"
          env: tags=@${{inputs.test-tags}}
      - uses: actions/upload-artifact@v3
        with:
          working-directory: test
          name: cucumber-reports
          path: test/cypress/cucumber-report
