---
name: UI automation lint check
on:
  pull_request:
    paths:
      - "test/**"

defaults:
  run:
    working-directory: test

permissions:
  id-token: write
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint