---
name: uitest
on: 
  workflow_dispatch:
    inputs:
      test-tags:
        type: choice
        required: true
        description: 'Select specific tag to be tested'
        options:
        - regression
        - letter-template
      environment:
        type: choice
        required: true
        description: 'Select test environment'
        options:
        - https://app.test.medirecords.com/
        - https://uitest.test.medirecords.com/


jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          runTests: false

  mrtest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          runTests: false
      - uses: cypress-io/github-action@v5
        with:
          install: false
          wait-on: '${{inputs.environment}}'
          browser: ${{ matrix.browser }}
          record: true
          parallel: false
          env: tags=@{{inputs.test-tags}}
          config: "baseUrl=${{inputs.environment}}"
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: test-report
      #     path: test-reports
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: cypress-videos
      #     path: cypress/vidoes
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: cypress-screenshots
      #     path: cypress/screenshots

